service: wdio-lambda-runner
custom: ${file(./runner-config.json)}

provider:
    name: aws
    runtime: nodejs6.10
    environment: ${self:custom.environment}
    timeout: 300

functions:
    run:
        handler: handler.run
        events: # All events associated with this function
            - http:
                path: run
                method: post

package:
    include: ${self:custom.package.include}
    exclude: ${self:custom.package.exclude}
